### ISSUE TITLE
生成的TS文件3分钟左右后失效

### ISSUE THREAD

**Issue by angelzlz** [Jsnails/MUX_TS#1]
https://github.com/Jsnails/
感谢作者，合成的TS很流畅，但有个小issues报告下。现象如下：
1. 直接用代码生成运行，生成的TS文件[时长大约5分钟]，用VLC或者EasyICE播放，在0-3分钟[左右]很正常，3分钟[左右]后的就没有图像了。请问是什么状况。
可以提供对应的TS文件，谢谢！

**Comment by Jsnails** [comment]
你那边是否加入了AAC音频，如果是加入了音频的话，建议先取消音频看看效果。再或者抓包或者用ts文件分析工具看看3分钟后面是否视频包打入了ts文件里面。不客气。
